services:
  db:
    image: postgis/postgis:15-3.4
    env_file:
      - .env/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      sotm_net:
        external: true
        name: sotmlat2025_sotm_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d osmdata"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana-oss:latest
    env_file:
      - .env/grafana.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - sotm_net

  loader:
    image: loader:latest
    env_file:
      - .env/db.env
    volumes:
      - ./src:/app
    command: ["./wait-for-db.sh", "db", "python3", "main.py"]
    networks:
      - sotm_net
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgis_data:
  grafana_data:

networks:
  sotm_net:
    external: true
    name: sotmlat2025_sotm_net
